alias ls='ls --color=auto'
alias chrome='chromium'
alias feh='feh --geometry 1500x1000 --scale-down'
alias open='xdg-open'
alias hibernate='systemctl hibernate'
alias suspend='systemctl suspend'
alias ranger='ranger --choosedir=$HOME/.cache/ranger/rangerdir; cd $(cat $HOME/.cache/ranger/rangerdir)'
